services:
  wordpress1:
    build: .
    ports:
      - 80:80
  wordpress2:
    build: .
    ports:
      - 80:80
  wordpress3:
    build: .
    ports:
      - 80:80
  wordpress4:
    build: .
    ports:
      - 80:80
  wordpress5:
    build: .
    ports:
      - 80:80
  wordpress6:
    build: .
    ports:
      - 80:80
  wordpress7:
    build: .
    ports:
      - 80:80
  wordpress8:
    build: .
    ports:
      - 80:80
  wordpress9:
    build: .
    ports:
      - 80:80
  wordpress10:
    build: .
    ports:
      - 80:80
